import React from 'react';

export function SectionFooter_SectionFooter() {
  return (
    <footer data-section-id="section_footer" data-section-type="footer" className="py-10 mt-auto" style={{ backgroundColor: 'var(--color-text)', color: 'var(--color-surface)', '--color-text': 'var(--color-surface)', '--color-muted': 'rgba(255,255,255,0.72)', '--color-surface': 'rgba(255,255,255,0.08)' }}>
      <div className="max-w-7xl mx-auto px-6 flex flex-col gap-6">
        <div className="text-center"><span className="text-xl font-bold tracking-tight" style={{ color: 'var(--color-text)', fontFamily: 'var(--font-heading)' }}>Sklep Kafe</span></div>
        <div className="text-center max-w-3xl mx-auto flex flex-col gap-3"><div dangerouslySetInnerHTML={{ __html: "<p data-block-id=\"block_footer_tagline\" data-block-type=\"text.paragraph\" style=\"color:var(--color-text);line-height:1.6\">Káva, brunch a víno v srdci Pálavy. Dolní Věstonice, jižní Morava.</p>" }} />
          <div dangerouslySetInnerHTML={{ __html: "<p data-block-id=\"block_footer_copy\" data-block-type=\"text.paragraph\" style=\"color:var(--color-text);line-height:1.6\">© 2025 Sklep Kafe – Dolní Věstonice. Všechna práva vyhrazena.</p>" }} /></div>
        <div className="flex flex-col items-center gap-3"><div dangerouslySetInnerHTML={{ __html: "<nav data-block-id=\"block_footer_nav\" data-block-type=\"nav_links\" style=\"display:flex;flex-wrap:wrap;justify-content:center;gap:1rem\"><a href=\"#o-miste\" style=\"color:var(--color-text);font-weight:500\">O místě</a><a href=\"#nabidka\" style=\"color:var(--color-text);font-weight:500\">Nabídka</a><a href=\"#galerie\" style=\"color:var(--color-text);font-weight:500\">Galerie</a><a href=\"#recenze\" style=\"color:var(--color-text);font-weight:500\">Recenze</a><a href=\"#kontakt\" style=\"color:var(--color-text);font-weight:500\">Kontakt</a></nav>" }} />
          <div dangerouslySetInnerHTML={{ __html: "<div data-block-id=\"block_footer_social\" data-block-type=\"social_links\" style=\"display:flex;flex-wrap:wrap;gap:.75rem\"><a href=\"https://www.instagram.com/\" style=\"display:inline-flex;align-items:center;padding:.55rem .95rem;border-radius:9999px;background:var(--color-surface);border:1px solid rgba(0,0,0,.08);color:var(--color-text);font-weight:500\">Instagram</a><a href=\"https://www.facebook.com/\" style=\"display:inline-flex;align-items:center;padding:.55rem .95rem;border-radius:9999px;background:var(--color-surface);border:1px solid rgba(0,0,0,.08);color:var(--color-text);font-weight:500\">Facebook</a></div>" }} /></div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div dangerouslySetInnerHTML={{ __html: "<div data-block-id=\"block_footer_address\" data-block-type=\"contact_info\" style=\"padding:1rem 1.25rem;border-radius:1rem;background:var(--color-surface);border:1px solid rgba(0,0,0,.08)\"><strong style=\"display:block;color:var(--color-text);margin-bottom:.25rem\">Adresa</strong><span style=\"color:var(--color-muted)\">Dolní Věstonice 296, 691 29 Dolní Věstonice</span></div>" }} />
          <div dangerouslySetInnerHTML={{ __html: "<div data-block-id=\"block_footer_phone\" data-block-type=\"contact_info\" style=\"padding:1rem 1.25rem;border-radius:1rem;background:var(--color-surface);border:1px solid rgba(0,0,0,.08)\"><strong style=\"display:block;color:var(--color-text);margin-bottom:.25rem\">Telefon</strong><span style=\"color:var(--color-muted)\">+420 603 576 670</span></div>" }} />
          <div dangerouslySetInnerHTML={{ __html: "<div data-block-id=\"block_footer_email\" data-block-type=\"contact_info\" style=\"padding:1rem 1.25rem;border-radius:1rem;background:var(--color-surface);border:1px solid rgba(0,0,0,.08)\"><strong style=\"display:block;color:var(--color-text);margin-bottom:.25rem\">E-mail</strong><span style=\"color:var(--color-muted)\">v.macanova@seznam.cz</span></div>" }} />
          <div dangerouslySetInnerHTML={{ __html: "<div data-block-id=\"block_footer_ico\" data-block-type=\"contact_info\" style=\"padding:1rem 1.25rem;border-radius:1rem;background:var(--color-surface);border:1px solid rgba(0,0,0,.08)\"><strong style=\"display:block;color:var(--color-text);margin-bottom:.25rem\">IČO</strong><span style=\"color:var(--color-muted)\">IČO: 123 45 678</span></div>" }} /></div>
        
      </div>
    </footer>
  );
}
